AWSTemplateFormatVersion: 2010-09-09
Parameters:
  MyBucketName:
    Type: String
    Description: "請輸入 S3 Bucket 的名稱"

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref MyBucketName